### ISSUE TITLE
Is there some benchmark data?

### ISSUE THREAD

**Issue by YuleiXiao** [logcabin/logcabin#188]
Is there some benchmark information about logcabin performance?

**Comment by ongardie** [comment]
There's some information in chapter 10 of my [PhD dissertation](https://github.com/ongardie/dissertation/). However, that was done on a different version of the code. The current code has progressed a fair bit, so it may be better and worse in some regards. LogCabin master is specifically missing pipelining (#97), since the implementation wasn't quite ready to merge. See #95 for some more background.

**Comment by ongardie** [comment]
Closing this issue. Feel free to re-open if you have more questions.
